### ISSUE TITLE
build failed no cordova - IOS

### ISSUE THREAD

**Issue by Malkafly** [In-Loco-Media/inlocomedia-cordova-plugin#2]
Oi!

Adicionei o plugin via cordova, segui os passos do link: http://docs.inlocomedia.com/docs/cordova-get-started
mas o app não compila pra IOS, segue o erro abaixo:

In file included from /Users/malkafly/projetos/MeuAPPX/MeuAPPX-app/platforms/ios/MeuAPPX/Plugins/inlocomedia-cordova-plugin/ILMCordovaPlugin.m:8:
MeuAPPX/Plugins/inlocomedia-cordova-plugin/ILMCordovaPlugin.h:10:9: fatal error: 'PluginAdapterDelegate.h' file not found
#import "PluginAdapterDelegate.h"
        ^
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/malkafly/Library/Developer/Xcode/DerivedData/MeuAPPX-bpdylbkdnfpvtohkjeocjeavbayb/Build/Intermediates/MeuAPPX.build/Release-iphonesimulator/MeuAPPX.build/Objects-normal/i386/ILMCordovaPlugin.o MeuAPPX/Plugins/inlocomedia-cordova-plugin/ILMCordovaPlugin.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/malkafly/projetos/MeuAPPX/MeuAPPX-app/platforms/ios/cordova/build-release.xcconfig,-workspace,MeuAPPX.xcworkspace,-scheme,MeuAPPX,-configuration,Release,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone SE,build,CONFIGURATION_BUILD_DIR=/Users/malkafly/projetos/MeuAPPX/MeuAPPX-app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/malkafly/projetos/MeuAPPX/MeuAPPX-app/platforms/ios/build/sharedpch

**Comment by falconegabriel** [comment]
Olá Malkafly,

Poderia me informar para qual versão do Cordova você está fazendo o build?

Abraços,

**Comment by Malkafly** [comment]
@falconegabriel  segue minhas infos:

global packages:
    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Gulp CLI         : CLI version 3.9.1 Local version 3.9.1
    Ionic CLI        : 3.4.0

local packages:
    @ionic/cli-plugin-cordova : 1.4.0
    @ionic/cli-plugin-gulp    : 1.0.1
    @ionic/cli-plugin-ionic1  : 2.0.0
    Cordova Platforms         : android 6.2.3 ios 4.4.0
    Ionic Framework           : ionic1 1.3.1

System:
    Node       : v6.10.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 3.10.10

**Comment by marcel-reboucas** [comment]
Oi @Malkafly,

o arquivo PluginAdapterDelegate.h está presente em uma dependência (cordova-plugin-extension) no plugin da AdMob (cordova-plugin-admobpro). O plugin da In Loco Media não está adicionando essa dependência, o que é uma falha, e a documentação precisa ser refeita/atualizada.

Como o plugin do Cordova da InLocoMedia funciona apenas com mediação, é necessário adicionar o plugin da mediação (ex. AdMob).

Você poderia verificar se utilizando `cordova plugin add cordova-plugin-admobpro` no projeto resolveria?

Lançaremos um update do plugin em breve e iremos corrigir a documentação para resolver esses problemas.

Abraço

**Comment by Malkafly** [comment]
Vou testar hoje a tarde, mas pelo que pesquisei parece ser isso mesmo, logo lhe retorno com feedback!
